server:
  port: 8502

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

spring:
  application:
    name: user-service
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver